

#ifndef USB_REQUEST_H
#define USB_REQUEST_H


enum {

	USB_REQUEST_RCPT_DEVICE    = 0 << 0,
	USB_REQUEST_RCPT_INTERFACE = 1 << 0,
	USB_REQUEST_RCPT_ENDPOINT  = 2 << 0,
	USB_REQUEST_RCPT_OTHER     = 3 << 0,

	USB_REQUEST_TYPE_STANDARD = 0 << 5,
	USB_REQUEST_TYPE_CLASS    = 1 << 5,
	USB_REQUEST_TYPE_VENDOR   = 2 << 5,

	USB_REQUEST_DIR_H2D = 0 << 7,
	USB_REQUEST_DIR_D2H = 1 << 7

};


enum {

	USB_REQUEST_BMRQTYPE = 0,
	USB_REQUEST_BRQST    = 1,
	USB_REQUEST_WVAL_L   = 2,
	USB_REQUEST_WVAL_H   = 3,
	USB_REQUEST_WIDX_L   = 4,
	USB_REQUEST_WIDX_H   = 5,
	USB_REQUEST_WLEN_L   = 6,
	USB_REQUEST_WLEN_H   = 7

};


#define USB_MKRQID(rqtype, type)   WORD2((rqtype), (type))

#define USB_REQUEST_TYPE(rqst)       WORD2((rqst)[USB_REQUEST_BMRQTYPE], (rqst)[USB_REQUEST_BRQST])
#define USB_REQUEST_WVALUE_L(rqst)   ((rqst)[USB_REQUEST_WVAL_L])
#define USB_REQUEST_WVALUE_H(rqst)   ((rqst)[USB_REQUEST_WVAL_H])
#define USB_REQUEST_WVALUE(rqst)     WORD2(USB_REQUEST_WVALUE_L(rqst),   USB_REQUEST_WVALUE_H(rqst))
#define USB_REQUEST_WINDEX(rqst)     WORD2((rqst)[USB_REQUEST_WIDX_L],   (rqst)[USB_REQUEST_WIDX_H])
#define USB_REQUEST_WLENGTH(rqst)    WORD2((rqst)[USB_REQUEST_WLEN_L],   (rqst)[USB_REQUEST_WLEN_H])


enum {

	USB_REQUEST_DEVICE_IN  = USB_REQUEST_DIR_D2H | USB_REQUEST_TYPE_STANDARD | USB_REQUEST_RCPT_DEVICE,
	USB_REQUEST_DEVICE_OUT = USB_REQUEST_DIR_H2D | USB_REQUEST_TYPE_STANDARD | USB_REQUEST_RCPT_DEVICE,

	USB_REQUEST_INTERFACE_IN  = USB_REQUEST_DIR_D2H | USB_REQUEST_TYPE_STANDARD | USB_REQUEST_RCPT_INTERFACE,
	USB_REQUEST_INTERFACE_OUT = USB_REQUEST_DIR_H2D | USB_REQUEST_TYPE_STANDARD | USB_REQUEST_RCPT_INTERFACE,

	USB_REQUEST_ENDPOINT_IN  = USB_REQUEST_DIR_D2H | USB_REQUEST_TYPE_STANDARD | USB_REQUEST_RCPT_ENDPOINT,
	USB_REQUEST_ENDPOINT_OUT = USB_REQUEST_DIR_H2D | USB_REQUEST_TYPE_STANDARD | USB_REQUEST_RCPT_ENDPOINT

};


enum {

	USB_REQUEST_GET_STATUS        = 0x00,
	USB_REQUEST_CLEAR_FEATURE     = 0x01,
	USB_REQUEST_SET_FEATURE       = 0x03,
	USB_REQUEST_SET_ADDRESS       = 0x05,
	USB_REQUEST_GET_DESCRIPTOR    = 0x06,
	USB_REQUEST_SET_DESCRIPTOR    = 0x07,
	USB_REQUEST_GET_CONFIGURATION = 0x08,
	USB_REQUEST_SET_CONFIGURATION = 0x09,
	USB_REQUEST_GET_INTERFACE     = 0x0a,
	USB_REQUEST_SET_INTERFACE     = 0x0b,
	USB_REQUEST_SYNC_FRAME        = 0x0c

};


enum {

	USB_REQUEST_GET_DEVICE_STATUS    = USB_MKRQID(USB_REQUEST_DEVICE_IN,    USB_REQUEST_GET_STATUS),
	USB_REQUEST_GET_INTERFACE_STATUS = USB_MKRQID(USB_REQUEST_INTERFACE_IN, USB_REQUEST_GET_STATUS),
	USB_REQUEST_GET_ENDPOINT_STATUS  = USB_MKRQID(USB_REQUEST_ENDPOINT_IN,  USB_REQUEST_GET_STATUS),

	USB_REQUEST_CLEAR_DEVICE_FEATURE    = USB_MKRQID(USB_REQUEST_DEVICE_OUT,    USB_REQUEST_CLEAR_FEATURE),
	USB_REQUEST_CLEAR_INTERFACE_FEATURE = USB_MKRQID(USB_REQUEST_INTERFACE_OUT, USB_REQUEST_CLEAR_FEATURE),
	USB_REQUEST_CLEAR_ENDPOINT_FEATURE  = USB_MKRQID(USB_REQUEST_ENDPOINT_OUT,  USB_REQUEST_CLEAR_FEATURE),

	USB_REQUEST_SET_DEVICE_FEATURE    = USB_MKRQID(USB_REQUEST_DEVICE_OUT,    USB_REQUEST_SET_FEATURE),
	USB_REQUEST_SET_INTERFACE_FEATURE = USB_MKRQID(USB_REQUEST_INTERFACE_OUT, USB_REQUEST_SET_FEATURE),
	USB_REQUEST_SET_ENDPOINT_FEATURE  = USB_MKRQID(USB_REQUEST_ENDPOINT_OUT,  USB_REQUEST_SET_FEATURE),

	USB_REQUEST_SET_DEVICE_ADDRESS = USB_MKRQID(USB_REQUEST_DEVICE_OUT, USB_REQUEST_SET_ADDRESS),

	USB_REQUEST_GET_DEVICE_DESCRIPTOR = USB_MKRQID(USB_REQUEST_DEVICE_IN,  USB_REQUEST_GET_DESCRIPTOR),
	USB_REQUEST_SET_DEVICE_DESCRIPTOR = USB_MKRQID(USB_REQUEST_DEVICE_OUT, USB_REQUEST_SET_DESCRIPTOR),

	USB_REQUEST_GET_DEVICE_CONFIGURATION = USB_MKRQID(USB_REQUEST_DEVICE_IN,  USB_REQUEST_GET_CONFIGURATION),
	USB_REQUEST_SET_DEVICE_CONFIGURATION = USB_MKRQID(USB_REQUEST_DEVICE_OUT, USB_REQUEST_SET_CONFIGURATION),

	USB_REQUEST_GET_INTERFACE_SETTING = USB_MKRQID(USB_REQUEST_INTERFACE_IN,  USB_REQUEST_GET_INTERFACE),
	USB_REQUEST_SET_INTERFACE_SETTING = USB_MKRQID(USB_REQUEST_INTERFACE_OUT, USB_REQUEST_SET_INTERFACE),

	USB_REQUEST_SYNC_ENDPOINT = USB_MKRQID(USB_REQUEST_ENDPOINT_IN,  USB_REQUEST_SYNC_FRAME)

};


#endif
